[package]
name = "arb-core"
version.workspace = true
edition.workspace = true

[dependencies]
alloy-primitives.workspace = true
alloy-signer.workspace = true
alloy-signer-local.workspace = true
alloy-sol-types.workspace = true
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-rlp.workspace = true

serde.workspace = true
serde_json.workspace = true
hex.workspace = true
thiserror.workspace = true
rust_decimal = { version = "1.0", features = ["serde-float", "serde-arbitrary-precision"] }
dotenvy.workspace = true
once_cell.workspace = true

rand.workspace = true
rand_08.workspace = true

[dev-dependencies]
tokio.workspace = true
tempfile.workspace = true
