[package]
name = "pricing"
version.workspace = true
edition.workspace = true

[dependencies]
arb-core.workspace = true
arb-chain.workspace = true

alloy-primitives.workspace = true
alloy-sol-types.workspace = true
alloy-provider = { version = "1.5.2", features = ["reqwest", "ws"] }
alloy-rpc-types.workspace = true
alloy-transport-http.workspace = true
alloy-network.workspace = true

tokio.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
clap.workspace = true
dotenvy.workspace = true
futures-util.workspace = true
url.workspace = true
rust_decimal.workspace = true

rustls = { version = "0.23", features = ["ring"] }
