[package]
name = "arb-chain"
version.workspace = true
edition.workspace = true

[dependencies]
arb-core.workspace = true

alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types.workspace = true
alloy-transport.workspace = true
alloy-transport-http.workspace = true
alloy-signer.workspace = true
alloy-network.workspace = true
alloy-sol-types.workspace = true

async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
futures.workspace = true
rust_decimal = { version = "1.0", features = ["serde-float", "serde-arbitrary-precision"] }
clap.workspace = true
chrono.workspace = true
anyhow.workspace = true
hex.workspace = true
colored.workspace = true
dotenvy.workspace = true
log = "0.4.30"
