name: CI

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Lint (Clippy)
        run: cargo clippy --all-targets -- -D warnings

      - name: Build Workspace
        run: cargo build --verbose

      - name: Run Anvil and Tests
        env:
          ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
        run: |
          anvil --fork-url "$ETH_RPC_URL" --port 8545 &

          until curl -s http://127.0.0.1:8545 > /dev/null; do
            echo "Waiting for Anvil..."
            sleep 1
          done

      - name: Run Tests
        run: cargo test --workspace
